FROM node:latest

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Expose the port that your Node.js app will run on
EXPOSE 3001

# Script to wait for the database
CMD ["npm", "run", "dev"]